import Config

# For production, don't forget to configure the url host
# to something meaningful, Phoenix uses this information
# when generating URLs.
#
# Note we also include the path to a cache manifest
# containing the digested version of static files. This
# manifest is generated by the mix phx.digest task
# which you should run after static files are built and
# before starting your production server.
config :viral_engine, ViralEngineWeb.Endpoint,
  cache_static_manifest: "priv/static/cache_manifest.json"

# Do not print debug messages in production
config :logger, :console,
  level: :info,
  format: "$time $metadata[$level] $message\n",
  metadata: [:request_id]

# ## SSL Support
#
# To get SSL working, you need to add the `https` configuration
# and set `force_ssl` to `true`:
#
#     config :viral_engine, ViralEngineWeb.Endpoint,
#       force_ssl: [hsts: true],
#       https: [
#         port: 443,
#         cipher_suite: :strong,
#         keyfile: "priv/cert/selfsigned_key.pem",
#         certfile: "priv/cert/selfsigned.pem",
#         cacertfile: "priv/cert/cacert.pem"
#       ]
#
# The `http:` config below can be replaced with:
#
#     https: [
#       port: 443,
#       cipher_suite: :strong,
#       keyfile: "priv/cert/selfsigned_key.pem",
#       certfile: "priv/cert/selfsigned.pem",
#       cacertfile: "priv/cert/cacert.pem"
#     ]
#
# Check `Plug.SSL` for all available options in `force_ssl`.

# ## Using releases
#
# If you are doing OTP releases, you need to instruct Phoenix
# to start each relevant endpoint:
#
#     config :viral_engine, ViralEngineWeb.Endpoint, server: true
#
# Then you can assemble a release by calling `mix release`.
# See `mix help release` for more information.
